# Generated by Django 4.2.7 on 2023-12-09 04:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='materials',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
